export { IAppLinking } from './contracts/IAppLinking';
export { AppLinkingFacade, ngfAppLinkingFacade } from './facades/AppLinkingFacade';
export { IContinuationManager } from './contracts/IContinuationManager';
export { ContinuationManagerFacade, ngfContinuationManagerFacade } from './facades/ContinuationManagerFacade';
// [HDSH] ShareKit 缺失，已裁剪
// export { ISystemShare } from './contracts/ISystemShare';
// [HDSH] ShareKit 缺失，已裁剪
// export { SystemShareFacade, ngfSystemShareFacade } from './facades/SystemShareFacade';
